name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "iniciendo login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin login"
    - name: Docker build Image
      run: |
        docker build -t valencia2002/docker-action:0.0.1 .

    - name: Push docker Image
      run: |
        docker push valencia2002/docker-action:0.0.1
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
